Library upgrades to swagger, jackson and guava
ORCID/orcid-model pull request #43
Opened 2023-01-09 13:16 UTC by Camelia-Orcid

2023-01-09 13:17 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update jersey server to 3.0.5](https://trello.com/c/qNy3Usbd/8362-update-jersey-server-to-305)

2023-01-10 15:33 UTC, amontenegro requested changes

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/record/CompletionDate.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/record/Citation.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice, line 15

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/record/Affiliation.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice, line 9

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/record/Address.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice, line 19

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/notification/permission/Item.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice, line 22

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/common/Year.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/common/Month.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice

2023-01-10 15:33 UTC, amontenegro commented on src/main/java/org/orcid/jaxb/model/v3/release/common/LastModifiedDate.java
> +import io.swagger.v3.oas.annotations.media.Schema;
Imported twice

2023-01-19 12:35 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bring jax-b version in orcid-model up to date](https://trello.com/c/8WGd6hWz/8459-bring-jax-b-version-in-orcid-model-up-to-date)

2023-01-20 08:22 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [[dependabot] Jackson databind](https://trello.com/c/APbSUFst/8458-dependabot-jackson-databind)

2023-01-23 15:31 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA] Remove release candidates from source code and Swagger](https://trello.com/c/zgjqmxCf/8124-qa-remove-release-candidates-from-source-code-and-swagger)

2023-01-30 21:47 UTC, amontenegro approved these changes

2023-01-30 21:47 UTC, merged